S = {
"Nevro": ("""We have entered into an Agreement and Plan of Merger (as it may be amended from time to time, the “Merger Agreement”), dated
as of February 6, 2025, with Globus Medical, Inc., a Delaware corporation (“Globus”), and Palmer Merger Sub Inc., a Delaware corporation. Such merger consideration represents (i) a premium of approximately 13.8% to the $5.13 closing price per
Company Share on the NYSE on February 4, 2025, the last full trading day prior to the approval by the board of directors of Nevro of the Merger on February 5, 2025 and (ii) a premium of approximately 39.0% to the trailing
volume-weighted average price per share of $4.20 for the thirty (30) calendar day period ended February 4, 2025.""", "Nevro Corp"),
"ProAssurance": ("""the Agreement and Plan of Merger, dated as of March 19, 2025 (as amended or modified from time to time, the “merger agreement”), among ProAssurance, The Doctors Company, and Jackson Acquisition Corporation, a wholly owned subsidiary of The Doctors Company (“Merger Sub”). Subject to the terms ... the right to receive $25.00 in cash, without interest ... which represents a premium of approximately 58.8% over ProAssurance’s closing stock price on March 18, 2025, the last trading day prior to the announcement of the merger agreement.""", "ProAssurance Corp"),
"ODP": ("""the Agreement and Plan of Merger, dated as of September 22, 2025 (as amended or modified from time to time, the “merger agreement”), among ODP, ACR Ocean Resources LLC (“Parent”), and Vail Holdings 1, Inc., a wholly owned subsidiary of Parent (“Merger Sub”). Subject to ... right to receive $28.00 in cash, without interest ... which represents a premium of approximately 34.5% over ODP’s closing stock price on September 19, 2025, the last trading day prior to the announcement of the merger agreement.""", "ODP Corp"),
"Enzo": ("""the Agreement and Plan of Merger (as it may be amended from time to time), dated as of June 23, 2025 (the “ Merger Agreement”), by and among the Company, Bethpage Parent, Inc., a Delaware corporation (“ Parent”), and Bethpage Merger Sub, Inc., a Delaware corporation and a wholly owned subsidiary of Parent (“ Merger Sub”), pursuant to which ... This per share price constitutes (i) a premium of approximately 32% over the closing price per share of Common Stock on June 23, 2025, the last full trading day prior to the Company’s announcement of its entry into the Merger Agreement, and (ii) a premium of approximately 23% over the volume weighted average price of Common Stock for the 30 -dayperiod ending June 23, 2025.""", "Enzo Biochem Inc"),
"Altus": ("""On February 5, 2025, we entered into an Agreement and Plan of Merger (as it may be amended from time to time, the “Merger Agreement”) ... The Merger Consideration represents a 66% premium to Altus Power’s closing stock price on October 15, 2025, the last trading day prior to the Company’s announcement of a formal review of strategic""", "Altus Power, Inc."),
"Monogram": ("""The $4.04 per share in upfront cash consideration to be paid for each share of Company common stock pursuant to the merger agreement represents a premium of approximately 23% over the closing price on July 11, 2025. On August 27, 2025, the latest practicable trading day ...""", "Monogram Technologies Inc."),
"FARO": ("""The Merger Consideration represents a premium of approximately 61% over the volume-weighted average price during the 30 calendar day period ending March 5, 2025 and a premium of approximately 40% over the closing price of FARO common stock on May 5, 2025, the latest trading day before the Merger Agreement was entered into and subsequently announced.""", "FARO Technologies Inc"),
"SpringWorks": ("""On April 27, 2025, SpringWorks entered into the Merger Agreement providing for the merger of Merger Sub ... The Merger Consideration represents a premium of 26% to SpringWorks’ unaffected 20-day volume-weighted average price of $37.38 on February 7, 2025, the day prior to the first market speculation of a""", "SpringWorks Therapeutics, Inc."),
"AvidXchange": ("""to the closing price of the Company Common Stock of $8.20 on May 6, 2025, the last trading day prior to the Company’s announcement of the execution of the Merger Agreement, a 16% premium over the 90-day volume weighted average price as of the same date and a 45% premium over the $6.89 closing price as of March 12, 2025, the last trading day before media reports of a potential transaction involving the Company.""", "AvidXchange Holdings, Inc."),
}
