"""RAG helpers: structured-table routing (no LLM for facts we already extracted), keyword re-rank, answer cache."""
import math, re, time, hashlib
from .ops import normalize_company
TOK = lambda s: re.findall(r"[a-z0-9]+", s.lower())

def route_question(q, deals):
    """If the question names a target we extracted and asks for premium/acquirer/date, answer from the table."""
    ql, qn = q.lower(), " " + normalize_company(q) + " "
    hit = [d for d in deals if normalize_company(d["target"]) and f" {normalize_company(d['target'])} " in qn]
    if not hit: return None
    want = [k for k, w in (("premium", ("premium",)), ("acquirer", ("acquirer", "acquire", "buyer", "bought", "who bought", "acquired by")), ("date", ("when", "date", "announce"))) if any(x in ql for x in w)]
    if not want: return None
    lines = []
    for d in hit[:3]:
        parts = []
        if "premium" in want: parts.append(f"premium {d['premium']}% ({d['premium_ref']})" if d["premium"] is not None else "no trusted premium extracted")
        if "acquirer" in want: parts.append(f"acquirer {d['acquirer']}")
        if "date" in want: parts.append(f"agreement date {d['ann_date']}")
        lines.append(f"{d['target']}: " + "; ".join(parts) + f" [confidence: {d['confidence']}]")
    return {"answer": "From the extracted table (not generated by the LLM): " + " | ".join(lines), "deals": [d["target"] for d in hit[:3]]}

def keyword_rerank(query, docs, metas, alpha=0.5):
    qt = set(TOK(query)) - {"the", "a", "of", "in", "to", "and", "is", "what", "for"}; n = len(docs)
    if not qt or n < 2: return docs, metas
    df = {t: sum(1 for d in docs if t in set(TOK(d))) for t in qt}; scored = []
    for i, d in enumerate(docs):
        tf = TOK(d); kw = sum((1 + math.log(1 + tf.count(t))) * math.log(1 + n / (1 + df[t])) for t in qt if t in tf) / (len(qt) or 1)
        scored.append((alpha * kw + (1 - alpha) * (1 - i / n), i))
    order = [i for _, i in sorted(scored, key=lambda x: -x[0])]
    return [docs[i] for i in order], [metas[i] for i in order]

_cache = {}
def cache_key(q): return hashlib.sha1(" ".join(TOK(q)).encode()).hexdigest()
def cache_get(q, ttl=3600, now=None):
    v = _cache.get(cache_key(q)); now = time.time() if now is None else now
    return v[1] if v and now - v[0] < ttl else None
def cache_put(q, val, now=None): _cache[cache_key(q)] = (time.time() if now is None else now, val)
